server:
  port: 9001
spring:
  application:
    name: tensquare-base

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.140.127.197:3306/tensquare_base?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #访问路径可以显示IP地址